input {
  file {
    path => "/home/ubuntu/elk-nlp-lab/logs/system.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}
filter {
  grok {
    match => { "message" => "\[(?<timestamp>\d{4}-\d{2}-\d{2})\] %{LOGLEVEL:level}: %{GREEDYDATA:msg}" }
  }
}
output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "compliance-logs"
  }
  stdout { codec => rubydebug }
}
